name: Build Hugo
on: push
    branches:
        - main
jobs:
    buildHugo:
        steps:
            - name: Git checkout
              uses: actions/checkout@latest

            - name: Setup Hugo
              uses: peaceiris/actions-hugo@v2
              with:
                hugo-version: '0.91.2'
              
            - name: Build Hugo
              run: hugo --minify
            
            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              if: ${{ github.ref == 'refs/heads/main' }}
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./public
